---

- name: For Red Hat family, disable firewalld
  when: ansible_os_family == 'RedHat'
  block:

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Disable firewalld on RedHat
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: no
        masked: yes
      when: ansible_facts.services['firewalld.service'] is defined

- name: Install iptables
  ansible.builtin.package:
    name: "{{ iptables_packages }}"
    state: present
