---

- name: For Red Hat family, disable firewalld
  block:

    - name: Populate service facts
      service_facts:

    - name: Disable firewalld on RedHat
      systemd:
        name: firewalld
        state: stopped
        enabled: no
        masked: yes
      when: ansible_facts.services['firewalld.service'] is defined

  when: ansible_os_family == 'RedHat'

- name: Install iptables
  package:
    name: "{{ iptables_packages }}"
    state: present
