---

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Include install.yml
  ansible.builtin.include_tasks: install.yml
- name: Include config.yml
  ansible.builtin.include_tasks: config.yml
- name: Include setup.yml
  ansible.builtin.include_tasks: setup.yml
  when: iptables_setup | bool
