---

- name: Start by flushing the active configuration
  ansible.builtin.iptables:
    flush: true
  become: yes
  when: iptables_flush | bool

- name: Set the default policy for each chain
  ansible.builtin.iptables:
    chain: "{{ item.name }}"
    policy: "{{ item.policy }}"
  become: yes
  loop: "{{ iptables_chains }}"

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Allow incoming ICMP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
  become: yes
  when: iptables_allow_icmp

- name: Allow loopback
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  become: yes
  when: iptables_allow_loopback

- name: Allow SSH traffic
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ item.proto }}"
    destination_port: "{{ item.port }}"
    ctstate: "{{ 'NEW' if item.proto == 'tcp' else omit }}"
    syn: "{{ 'match' if item.proto == 'tcp' else omit }}"
    jump: ACCEPT
  become: yes
  loop: "{{ iptables_incoming_rules }}"

- name: Save running rules to file
  community.general.iptables_state:
    state: saved
    path: "{{ iptables_state }}"
