---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  tasks:
    - name: Include role 'ansible-role-iptables'
      ansible.builtin.include_role:
        name: ansible-role-iptables
